title: Data Science for Life-Science by Michal
email: michal.bozydar.kowalski@gmail.com
description: Data Science for Life-Science
baseurl:
linkedin: linkedin.com/in/michalkowalski94/
github: github.com/michalkowalski94
markdown: kramdown
theme: minima
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - jekyll-admin
